### ISSUE TITLE
Not working with yew 0.21.0

### ISSUE THREAD

**Issue by jreniel** [aleb2000/split-yew#1]
error[E0277]: the trait bound `split_yew::Split: yew::Component` is not satisfied                                     
  --> ui/src/components/app/app.rs:12:10                                                                              
   |                                                                                                                  
12 |         <Split>                                                                                                  
   |          ^^^^^ the trait `yew::Component` is not implemented for `split_yew::Split`                              
   |                                                                                                                  
   = help: the trait `yew::Component` is implemented for `ContextProvider<T>`                                         
   = note: required for `split_yew::Split` to implement `yew::BaseComponent`                                          
   = note: this error originates in the macro `html` (in Nightly builds, run with -Z macro-backtrace for more info)   
                                                                                                                      
error[E0599]: the function or associated item `new` exists for struct `VChild<Split>`, but its trait bounds were not s
atisfied                                                                                                              
  --> ui/src/components/app/app.rs:12:10                                                                              
   |                                                                                                                  
12 |         <Split>                                                                                                  
   |          ^^^^^ function or associated item cannot be called on `VChild<Split>` due to unsatisfied trait bounds   
   |                                                                                                                  
  ::: .cargo/git/checkouts/split-yew-84a544648acafcab/8548d2a/src/lib.rs:99:1                           
   |                                                                                                                  
99 | pub struct Split {                                                                                               
   | ---------------- doesn't satisfy `split_yew::Split: yew::BaseComponent`                                          
   |                                                                                                                  
   = note: the following trait bounds were not satisfied:                                                             
           `split_yew::Split: yew::BaseComponent`                                                                     
   = note: this error originates in the macro `html` (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by aleb2000** [comment]
Yes, I have not updated to 0.21 yet, as I was busy with other things. I will do that today.

**Comment by aleb2000** [comment]
I have updated to use Yew `0.21.0`. You can update to the latest version (`0.2.0`) and it should now work. I will close this issue. I have tested it on my own project and it works as expected, but you can always open a new issue if you find some bug. Thanks for the report!

**Comment by jreniel** [comment]
Thank YOU for making this, for making it available for all of us to use, and for your super quick bug fix response! @aleb2000 FTW!
=)
